
--1.
CREATE TABLE archiwum_departamentow (
    department_id NUMBER,
    department_name VARCHAR2(50),
    close_date DATE,
    last_manager_first_name VARCHAR2(50),
    last_manager_last_name VARCHAR2(50)
);
/
CREATE OR REPLACE TRIGGER trg_after_department_delete
AFTER DELETE ON departments
FOR EACH ROW
DECLARE
    v_first_name employees.first_name%TYPE;
    v_last_name employees.last_name%TYPE;
BEGIN
    SELECT e.first_name, e.last_name INTO v_first_name, v_last_name
    FROM employees e
    WHERE e.employee_id = :OLD.manager_id;
    INSERT INTO archiwum_departamentow (department_id, department_name, close_date, last_manager_first_name, last_manager_last_name)
    VALUES (:OLD.department_id, :OLD.department_name, SYSDATE, v_first_name, v_last_name);
END;
/


--2.
CREATE TABLE złodziej (
    change_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(30),
    czas_zmiany DATE
);
/
CREATE OR REPLACE TRIGGER trg_check_employee_salary
BEFORE INSERT OR UPDATE ON employees
FOR EACH ROW
BEGIN
    IF :NEW.salary < 2000 OR :NEW.salary > 26000 THEN
        INSERT INTO złodziej (username, czas_zmiany)
        VALUES (USER, SYSDATE);
        RAISE_APPLICATION_ERROR(-20020, 'Salary must be between 2000 and 26000.');
    END IF;
END;
/


--3.
CREATE SEQUENCE emp_id_seq START WITH 1;
CREATE OR REPLACE TRIGGER trg_emp_id_auto_increment
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
    SELECT emp_id_seq.NEXTVAL INTO :NEW.employee_id FROM dual;
END;
/


--4.
CREATE OR REPLACE TRIGGER trg_restrict_job_grades
BEFORE INSERT OR UPDATE OR DELETE ON job_grades
BEGIN
    RAISE_APPLICATION_ERROR(-20030, 'Operations on job_grades table are not allowed.');
END;
/


--5.
CREATE OR REPLACE TRIGGER trg_prevent_job_salary_update
BEFORE UPDATE OF max_salary, min_salary ON jobs
FOR EACH ROW
BEGIN
    :NEW.max_salary := :OLD.max_salary;
    :NEW.min_salary := :OLD.min_salary;
END;
/


--6.

--1.
DELETE FROM departments WHERE department_id = 10;
SELECT * FROM archiwum_departamentow WHERE department_id = 10;
--2.
BEGIN
    INSERT INTO employees (first_name, last_name, email, salary)
    VALUES ('abc', 'def', 'a@a.net', 1000);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
SELECT * FROM złodziej WHERE username = USER;
--3.
INSERT INTO employees (first_name, last_name, email, salary)
VALUES ('abc', 'xyz', 'a@a.net', 3000);
SELECT * FROM employees WHERE first_name = 'abc' AND last_name = 'xyz';
--4.
BEGIN
    INSERT INTO job_grades (grade_level, lowest_sal, highest_sal)
    VALUES (10, 5000, 15000);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
--5.
DECLARE
    v_old_min_salary jobs.min_salary%TYPE;
    v_old_max_salary jobs.max_salary%TYPE;
BEGIN
    SELECT min_salary, max_salary INTO v_old_min_salary, v_old_max_salary FROM jobs WHERE job_id = 'IT_PROG';
    UPDATE jobs SET min_salary = 6000, max_salary = 20000 WHERE job_id = 'IT_PROG';
    IF v_old_min_salary = (SELECT min_salary FROM jobs WHERE job_id = 'IT_PROG') AND
       v_old_max_salary = (SELECT max_salary FROM jobs WHERE job_id = 'IT_PROG') THEN
        DBMS_OUTPUT.PUT_LINE('niezmienione wynagrodzenia');
    ELSE
        DBMS_OUTPUT.PUT_LINE('zmienione wynagrodzenia');
    END IF;
END;
/